#以下为JWT的配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Zh-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /index/**,/login/**,/favicon.ico
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  tomcat:
    max-threads: 100  # Tomcat 最大线程数

spring:
  datasource:
    hikari:
      register-mbeans: true   # 配置 Hikari 连接池 JMX MBean 注册连接池相关信息
      max-lifetime: 60000     # 存活时间
