server:
  port: 10240
spring:
  profiles:
    active: @profiles.active@
  datasource:
    # 基础属性
    # 腾讯云 mysql 数据库连接
    url: jdbc:mysql://47.111.158.6:3306/code-fusheng?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: Xcode-mysql?
    # 可以不配置，根据url自动识别，建议配置
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    rest:
      uris: 42.192.222.62:9200
  redis:
    host: 42.192.222.62
    port: 6390
    password: Xcode-redis?
    database: 7
  data:
    mongodb:
      uri: mongodb://admin:123456@42.192.222.62:27017/code-fusheng?authSource=admin
#以下为JWT的配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Zh-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /index/**,/login/**,/favicon.ico


