server:
  port: 8080
spring:
  profiles:
    active: @profiles.active@
  datasource:
    # 基础属性
    # 腾讯云 mysql 数据库连接
    url: jdbc:mysql://47.111.158.6:3306/code-fusheng?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: Xcode-mysql?
    # 可以不配置，根据url自动识别，建议配置
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    rest:
      uris: 42.192.222.62:9200
